### ISSUE TITLE
Add command `joke`

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/trap#15]
Print a random joke about PHP

---

Or print a joke of the day on start

**Comment by k2gl** [comment]
I'm on it.

**Comment by roxblnfk** [comment]
Do you have a jokes list already? :D

**Comment by k2gl** [comment]
> Do you have a jokes list already? :D

![image](https://github.com/buggregator/trap/assets/2846079/f2f0cee9-1d6e-4093-99b7-88b933a16ef8)

https://github.com/buggregator/trap/pull/55

**Comment by k2gl** [comment]
Now the message has a background

![image](https://github.com/buggregator/trap/assets/2846079/d7169c8c-a595-4dfd-bd0e-14098e464cc6)

**Comment by roxblnfk** [comment]
The background should be with logo only. It's part of logo.

However, it's necessary to consider the message length and screen width.
If the screen width is less than the message length and message bubble, then characters will be wrapped to a new line, and it will look terrible.

There are two solutions:
- Avoid using complex images.
- Aim for a screen width of 80 characters and manually insert line breaks within the bubble.
- Design it in such a way that changing the screen width does not affect the image quality, while the text does not care where the line break occurs automatically.

Symfony Console has a helper for determining terminal width, but it doesn't calculate it dynamically. Therefore, I would prefer the first or third option.

**Comment by k2gl** [comment]
Banana flavored version

![image](https://github.com/buggregator/trap/assets/2846079/4c973daf-8631-4298-a7ac-98e474b1ac5e)
