### ISSUE TITLE
PHPStorm: add `trap()` function into the EA Inspection

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/trap#35]
Add the `trap()` function into [`ForgottenDebugOutputInspector`](https://github.com/kalessil/phpinspectionsea/blob/b34274871f5689febd09d091a3c52961d7d2bf59/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java#L32C14-L32C44) there https://github.com/kalessil/phpinspectionsea

**Comment by k2gl** [comment]
https://github.com/kalessil/phpinspectionsea/pull/1942

**Comment by roxblnfk** [comment]
The PR has been merged. Thanks @k2gl
