### ISSUE TITLE
Add CS checker and fixer

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/trap#56]
Add CS checker and fixer that will:
- [x] Check the code for compliance with PER-2 https://github.com/buggregator/trap/pull/67
- [x] #68
- Take into account some custom aspects:
  - We use FQN for functions in the global namespace
  - We use FQN for classes in the global namespace
  
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer

**Comment by lotyp** [comment]
Will take this.

**Comment by lotyp** [comment]
Closing, as task is completed by these PR's

https://github.com/buggregator/trap/pull/88
https://github.com/buggregator/trap/pull/91
