### ISSUE TITLE
Automatically push Code Style fixes into Pull Requests and branches

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/trap#68]
Need to check that auto-push works well

**Comment by chachanagov** [comment]
Automatic fixes have been configured in the pull request #67

**Comment by roxblnfk** [comment]
Really? Nice! Need to check it

**Comment by roxblnfk** [comment]
@chachanagov looks like #69 hasn't got a commit with CS fixes.
Also CS check passed. Need to investigate it.
