### ISSUE TITLE
Integrate PestPHP for Enhanced Testing Support

### ISSUE THREAD

**Issue by lotyp** [buggregator/trap#80]
### Summary

I propose integrating [PestPHP](https://github.com/pestphp/pest) into `buggregator/trap`.

[PestPHP](https://github.com/pestphp/pest) is known for its elegant syntax and pretty console outputs, enhancing both readability and debugging capabilities.

### Reference Example
Please refer to this repository for a guide on integrating PestPHP with Laravel packages: [Laravel Package Template with PestPHP](https://github.com/wayofdev/laravel-package-tpl).

### Benefits
- Improved test readability and maintenance.
- Pretty console output for better debugging.
- Attracts a broader audience familiar with PestPHP.

**Comment by lotyp** [comment]
Sorry guys but I will take this 😀

**Comment by roxblnfk** [comment]
Don't convert unit tests into pest syntax. The pest syntax is terrible

**Comment by lotyp** [comment]
Added in: https://github.com/buggregator/trap/pull/81
